/*
 * This file is generated by jOOQ.
 */
package com.example.shigure.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 1850673445;

    private Long   id;
    private String username;
    private String password;
    private Byte   adminFlag;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.username = value.username;
        this.password = value.password;
        this.adminFlag = value.adminFlag;
    }

    public User(
        Long   id,
        String username,
        String password,
        Byte   adminFlag
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.adminFlag = adminFlag;
    }

    public Long getId() {
        return this.id;
    }

    public User setId(Long id) {
        this.id = id;
        return this;
    }

    public String getUsername() {
        return this.username;
    }

    public User setUsername(String username) {
        this.username = username;
        return this;
    }

    public String getPassword() {
        return this.password;
    }

    public User setPassword(String password) {
        this.password = password;
        return this;
    }

    public Byte getAdminFlag() {
        return this.adminFlag;
    }

    public User setAdminFlag(Byte adminFlag) {
        this.adminFlag = adminFlag;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(adminFlag);

        sb.append(")");
        return sb.toString();
    }
}
