/*
 * This file is generated by jOOQ.
 */
package com.example.shigure.jooq;


import com.example.shigure.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in shigure
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>shigure.user</code>.
     */
    public static final User USER = com.example.shigure.jooq.tables.User.USER;
}
